08-09RazorPage/LearnRazorPage/LearnRazorPage/Models/CompanySummary.cs
namespace LearnRazorPage.Models
{
    public class CompanySummary
    {
        public int EmployeeCount { get; set; }
        public int AverageDepartmentEmployeeCount { get; set; }
    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Models/Department.cs
using System.ComponentModel.DataAnnotations;

namespace LearnRazorPage.Models
{
    public class Department
    {
        //使用prop代码片段可以快速生成字段
        //prop + 两次tab
        public int Id { get; set; }
        [Display(Name = "部门名称")]
        public string Name { get; set; }
        public string Location { get; set; }
        public  int EmployeeCount { get; set; }
    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Models/Employee.cs
namespace LearnRazorPage.Models
{
    public class Employee
    {
        //使用prop代码片段可以快速生成字段
        //prop + 两次tab
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Gender Gender { get; set; }
        public bool Fired { get; set; }
    }

    public enum Gender
    {
        女 = 0,
        男 = 1
    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Pages/Department/AddDepartment.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LearnRazorPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LearnRazorPage.Pages.Department
{
    public class AddDepartmentModel : PageModel
    {
        private readonly IDepartmentService _departmentService;

        [BindProperty]
        public Models.Department Department { get; set; }

        public AddDepartmentModel(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _departmentService.Add(Department);
            return RedirectToPage("/Index");
        }
    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Pages/Employee/AddEmployee.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LearnRazorPage.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LearnRazorPage.Pages.Employee
{
    public class AddEmployeeModel : PageModel
    {
        private readonly IEmployeeService _employeeService;

        public AddEmployeeModel(IEmployeeService employeeService)
        {
            _employeeService = employeeService;
        }

        [BindProperty] public Models.Employee Employee { get; set; }

        public async Task<IActionResult> OnPostAsync(int departmentId)
        {
            Employee.DepartmentId = departmentId;

            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _employeeService.Add(Employee);

            return RedirectToPage("EmployeeList", new {departmentId});
        }


    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Pages/ViewComponents/CompanySummaryViewComponent.cs
using System.Threading.Tasks;
using LearnRazorPage.Services;
using Microsoft.AspNetCore.Mvc;

namespace LearnRazorPage.Pages.ViewComponents
{
    //CROR R+R重构（批量修改变量、方法名）
    public class CompanySummaryViewComponent:ViewComponent
    {
        private readonly IDepartmentService _departmentService;

        public CompanySummaryViewComponent(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        public async Task<IViewComponentResult> InvokeAsync(string title)
        {
            ViewBag.Title = title;
            var summary = await _departmentService.GetCompanySummary();
            return View(summary);
        }
    }
}

08-09RazorPage/LearnRazorPage/LearnRazorPage/Pages/Department/AddDepartment.cshtml
@page
@model LearnRazorPage.Pages.Department.AddDepartmentModel
<form asp-action="Add">
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.Name"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.Name" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.Location"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.Location" />
        </div>
    </div>
    <div class="row form-group">
        <div class="col-md-2 offset-md-2">
            <label asp-for="Department.EmployeeCount"></label>
        </div>
        <div class="col-md-6">
            <input class="form-control" asp-for="Department.EmployeeCount" />
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-md-2">
            <button type="submit" class="btn btn-primary">Add</button>
        </div>
    </div>
</form>

08-09RazorPage/LearnRazorPage/LearnRazorPage/Pages/Index.cshtml
@page
@using LearnRazorPage.Models
@using LearnRazorPage.Services

@inject IDepartmentService deparmentService

<div class="row">
    <div class="col-md-10 offset-md-2">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Employee Count</th>
                <th>操作</th>
            </tr>
            @Html.DisplayFor(x=>x.Departments)
        </table>
    </div>
</div>


<div class="row">
    <div class="col-md-4 offset-md-2">
        <a asp-page="Department/AddDepartment">Add</a>
    </div>
    <div class="col-md-4">
        @await Component.InvokeAsync("CompanySummary",new {title = "部门列表页的汇总"})
        <vc:company-summary title="部门列表页的汇总2"></vc:company-summary>
    </div>
</div>

@functions
{
    public IEnumerable<Models.Department> Departments { get; set; }

    //Get请求过来后走这个方法
    public async Task OnGetAsync()
    {
        
        Departments = await deparmentService.GetAll();
    }
}